add_aligner(merging gentle and vosk projects)
alphacep/vosk-api pull request #720
Opened 2021-10-14 10:19 UTC by Vadim-cloud-star

Main idea of the request was to replace m3.cc(language model)/k3.cc(acoustic model) with "model" and "KaldiRecognizer" methods of vosk to get more accurate and faster algorithms, which was achieved. At the moment it's still difficult to talk about exact numbers(now we're preparing huge data set for it) , but we can say that with current data set(aligner/example) 
gentle:
20-24 unaligned words after 1st aligning stage, and 2 unaligned words after 2nd
aligner:
0 unaligned words after 1st aligning stage(need to check more complex data sets, which we'll do exactly after that request)
Moreover speed of the aligner algorithm was increased about 2 times compare with gentle.

How to work(there are 2 ways):
1) Put your selected model into python/aligner/ then start it like:
python3 vosk_align.py example/lucier.wav example/lucier.txt model
(Hint: lucier.wav and lucier.txt is default examples, your examples can be different)
2) We changed setup.py either(script has been added), so you can start vosk_align.py script anywhere you want, main rule is provide aligner "right paths to wav, txt files and model folder", for default example and model spot it looks like(ls ~/ contain vosk-api):
vosk_align.py ~/vosk-api/python/aligner/example/lucier.wav ~/vosk-api/python/aligner/example/lucier.txt ~/vosk-api/python/aligner/model

2021-10-17 15:12 UTC, nshmyrev requested changes

2021-10-17 15:12 UTC, nshmyrev commented on python/aligner/vosk_align.py
> +parser.add_argument(
just "model"

2021-10-17 15:12 UTC, nshmyrev commented on python/aligner/vosk_align.py
> +        print("Not enough words to align, should be 3 or more")
No need for this restriction

2021-10-17 15:12 UTC, nshmyrev commented on python/vosk/aligner/language_model.py
> +        nlp = spacy.load('en_core_web_sm')
No need for spacy dependency here. Implement an easier algorithm that splits by punctuation.

2021-10-17 15:12 UTC, nshmyrev commented on python/vosk/aligner/util/cyst.py
> +# Twisted lazy computations
I this file ever used?

2021-10-17 15:12 UTC, nshmyrev commented on python/vosk/aligner/util/paths.py
> +import os
This  module is not really necessary too

2021-10-18 11:09 UTC, gullabi commented on python/vosk/aligner/language_model.py
> +    preprocess_result = preprocess(text) # 1
if there is a new line at the end of the text, the lm build hence the alignment fails. in order to fix it: `text` -> `text.strip()` needed.

2021-10-18 13:21 UTC, gullabi commented on python/vosk/aligner/multipass.py
> +def realign(alignment, amount, ms, mtt, progress_cb=None):
certain calls in realign need `model` hence it has to be added here as a variable

2021-10-18 13:21 UTC, gullabi commented on python/vosk/aligner/multipass.py
> +        task_ms = metasentence.MetaSentence(task_transcript)
metasentence needs `model` as a variable

2021-10-18 13:21 UTC, gullabi commented on python/vosk/aligner/multipass.py
> +        task_gen_hclg_filename = language_model.make_bigram_language_model(task_transcript + '.')
`make_bigram_language_model` needs `model` as a variable.

2021-10-18 13:21 UTC, gullabi commented on python/vosk/aligner/multipass.py
> +    for chunks in range(amount):
the multipass algorithm is not working as expected, the code fails here since `amount != len(to_realign)` when there are unaligned words after the first pass.

as a test case try running the given test case with the english aspire model from the vosk website. (error also affects alignment with other languages, or any case which realignment is needed.)

2021-10-18 15:30 UTC, vadimdddd commented on python/vosk/aligner/multipass.py
> +    for chunks in range(amount):
Thanks for your help. I will fix it couple with Nikolay questions.

2021-10-19 11:36 UTC, gullabi commented on python/vosk/aligner/multipass.py
> +    for chunks in range(amount):
Thanks for the answer. Just wanted to write about some detail that I couldn't really solve. I noticed a problem with the `MultiThreadedTranscriber.transcribe()`: For some files it does not transcribe until the end of the audio file. This might be related to the `amount != len(to_realign)` and it also causes other problems in `diff_align`. 

I am mentioning it because maybe you or Nikolay can see much easier if there is a bug in `MultiThreadedTranscriber.transcribe()`, if not I will try again from where I have left off, after your next fixes.

2021-11-05 10:28 UTC, closed without merging