add_transcriber
alphacep/vosk-api pull request #851
Opened 2022-02-11 20:49 UTC by Vadim-cloud-star

Transcriber allows you transcribe your audiofile. The project contain ffmpeg transform that allow you transcribe all ffmpeg formats. Also in result data you can see time of transcription and xRT.
How to work:
1) download model from here: https://alphacephei.com/vosk/models and place into transcriber directory
2) run the script(example): python3 vosk_transcriber.py . -i cats.wav
You can get result in terminal or choose output file like txt etc, it will look like: python3 vosk_transcriber.py . -i cats.wav -o cats.txt
In future commits we plan to add model's parser which will ask you 'what model do you need' then download and place it instead of you and 'folder handler' which will process full file directory instead of one file.

2022-02-22 17:20 UTC, ls-milkyway commented
Can the command ` python3 vosk_transcriber.py . -i cats.wav -o -o cats.txt ` generate subtitle file instead of text file (i.e. cats.srt rather than cats.txt)...If not, then plz modify the pull request by converting it to draft..& include srt file generation code..thanks

2022-02-22 17:27 UTC, nshmyrev commented
@ls-milkyway yes, srt option gonna be there.

2022-02-28 12:50 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +    logging.info('converting complite')
complete

2022-02-28 12:50 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +    logging.info('startting transcription')
starting

2022-02-28 12:50 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +    fh = open(outputdata, 'w', encoding='utf-8') if outputdata else sys.stdout
with open(outputdata, 'w', encoding='utf-8')  as fh

2022-02-28 12:50 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +    logging.info('program finished')
No need for such verbose logging

2022-02-28 12:50 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +    def process_dirs(model, inputdata, outputdata, outputtype, log):
just process_dir, not dirs

2022-03-09 14:12 UTC, Vadim-cloud-star commented
@ls-milkyway, Hello, test the program please, need feedback :)

2022-03-22 19:04 UTC, nshmyrev requested changes

2022-03-22 19:04 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +def calculate(model, inputdata, outputdata, outputtype, log):
Should be in the same folder as process_dir and named uniformly.

2022-03-22 19:04 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +    if list_models:
Must be executed before you run get_model and should exit after

2022-03-22 19:04 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +    print(f'''Script info: execution time: {sec} sec, {mcsec} mcsec; xRT: {format(tot_samples / 16000.0 / float(diff_end_start), '.3f')}''')
Should be log, not print

2022-03-22 19:04 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +    tot_samples = main(args.model, args.input, args.output, args.outputtype, args.list_models, args.model_name, args.lang, args.log)[1]
Its better to pass just args

2022-03-22 19:04 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        tot_samples = 0
Declare variables right before you use them

2022-03-22 19:04 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        WORDS_PER_LINE = 7
Declare constants in the header of the file

2022-03-22 19:04 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +                rec.SetWords(True)
This has to be run once

2022-03-22 19:04 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +            pre_link = 'https://alphacephei.com/vosk/models/'
This has to be a global constant

2022-03-22 19:04 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +            model_zip = str(model_path) + '/' + result_model + '.zip'
You'd better operate paths here, not string

2022-03-22 19:04 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        url = 'https://alphacephei.com/vosk/models/model-list.json'
This has to be a constant too

2022-03-22 19:04 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        model_arg = str(model_path) + '/' + result_model
What 'arg' means here in the name

2022-03-22 19:04 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        def check_model_path():
This method doesn't only check

2022-03-29 19:41 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        tot_samples = 0
Whats going on with this change

2022-03-29 19:41 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        response = requests.get(model_list_url)
No need to query model list every time you run the tool, only when you want to download the model

2022-03-29 19:41 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        def get_model_path():
No need for embedded methods

2022-03-29 19:41 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        if Path(model_location).exists():
No need for else here

2022-03-29 19:41 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        model_path = Path(get_model_path())
get_model_path already returns Path object

2022-03-29 19:41 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        def get_model_path():
This method also creates the folder, it must be reflected in method name

2022-03-29 19:41 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +import logging
This script has to be installed into bin script with setup.py machinery. It is missing from the patch

2022-03-29 19:41 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +        file_list = transcriber.process_dir(args)
"process dir" name is confusing here.

2022-03-29 19:41 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +    start_time = transcriber.get_time()
get_time/send_time are wrong method names

2022-04-05 20:19 UTC, nshmyrev requested changes

2022-04-05 20:19 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        if args.lang != 'en-us' or args.model_name != 'vosk-model-small-en-us-0.15':
Why en-us is so special?

2022-04-05 20:19 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +    def get_list_models():
models_list

2022-04-05 20:19 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +    def get_results(inputdata):
Avoid submethods

2022-04-05 20:19 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +    if Path(args.input).is_dir() and Path(args.output).is_dir():
What if args.input doesn't exist

2022-04-05 20:19 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        extension_i = f".{files[0].split('.')[1]}"
What if files have different extensions

2022-04-05 20:19 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +            if args.outputtype == 'txt':
If and else have the same effect

2022-04-05 20:19 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        return process
It returns stream, not process

2022-04-14 14:06 UTC, nshmyrev commented on python/setup.py
> +    version="0.3.33",
Remove this change from this patch

2022-04-14 14:06 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +    logging.info('complite')
complite

2022-04-14 14:06 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +        logging.info('Please set input arg')
argument, no short names in user output

2022-04-14 14:06 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +    logging.info(f'''Script info: execution time: {sec} sec, {mcsec} mcsec; xRT: {format(tot_samples / 16000.0 / float(diff_end_start), '.3f')}''')
remove "script info"

2022-04-14 14:06 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +    def get_file_list(args):
Simplify this method

2022-04-14 14:06 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        if args.outputtype == 'srt':
Merge ifs here with previous

2022-04-14 14:45 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +        return final_result, tot_samples
Missing else

2022-04-14 14:46 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +            data = process.stdout.read(4000)
Stream

2022-04-14 14:49 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        output_files = [input_files[name].replace(Path(input_files[name]).suffix, output_extension) for name in input_files]
Use https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.with_suffix

2022-04-18 15:59 UTC, nshmyrev requested changes

2022-04-18 15:59 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +    def get_start_time():
Avoid embedded methods

2022-04-18 15:59 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        model = Model(model_location)
Move this to get_model, it is not really download

2022-04-18 15:59 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        return result_model
rename to 'result'

2022-04-18 15:59 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +    def get_model_name_using_lang_arg(self, args, models_path):
rename to get_model_by_lang

2022-04-18 15:59 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +    def get_model_name_using_model_name_arg(self, args, models_path):
Rename to get_model_by_name

2022-04-18 15:59 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +                logging.info('model name "%s" does not exist, set -models_list to see available models' % (args.model_name))
"set" is not applicable to argument

2022-04-18 15:59 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        return result_model
Just 'result'

2022-04-18 15:59 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        def get_result_and_tot_samples(rec, data, tot_samples, result):
Avoid embedded methods

2022-04-18 15:59 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        def models_list():
Avoid embedded methods, start method name from a verb.

2022-04-18 15:59 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +        '-models_list', default=False, action='store_true',
Verb first

2022-04-18 15:59 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +            [language_list.append(language['lang']) for language in response.json() if language['lang'] not in language_list]
You can create language list here directly, not above

2022-04-18 15:59 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        [arg_list.append((Path(args.input, files), Path(args.output, Path(files).stem).with_suffix('.' + args.outputtype))) for files in os.listdir(args.input)]
You can create list here directly, without append. Bad pattern

2022-04-18 15:59 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +            logging.info('Please set correct input/output paths')
Specify directly what is missing

2022-04-19 18:06 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +parser.add_argument(
Add --help option to print usage

2022-04-19 21:46 UTC, nshmyrev requested changes

2022-04-19 21:46 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +            self.get_list_models()
Get or list

2022-04-19 21:46 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        tot_samples = 0
Still unsolved

2022-04-19 21:46 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +        help='select model current language type')
fix grammar

2022-04-19 21:46 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +        help='list of all available languages')
list available languages

2022-04-19 21:46 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +    logging.info('complete')
meaningless log

2022-04-19 21:46 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +        model = transcriber.get_model(args)
get model after arguments are verified

2022-04-19 21:46 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +        return final_result, tot_samples
Still valid

2022-04-19 21:46 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +        elif not Path(args.input).is_dir() or not Path(args.output).is_dir():
Just else without condition

2022-04-19 21:46 UTC, nshmyrev commented on python/transcriber/vosk_transcriber.py
> +                inputdata = (args.input, args.output)
select proper variable name

2022-04-19 21:46 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +                logging.info('model name "%s" does not exist, request -models_list to see available models' % (args.model_name))
there is no model_list anymore

2022-04-19 21:46 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +        model_location = str(Path(models_path, result))
No need to convert to string here and back in the next line

2022-04-19 21:46 UTC, nshmyrev commented on python/transcriber/transcriber.py
> +            urllib.request.urlretrieve(MODEL_PRE_PATH + model_location[len(srt(Path(model_location).parent))+1:] + '.zip', model_zip)
What is srt here

2022-04-20 11:48 UTC, merged